### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by whuhxb** [QingyongHu/SensatUrban#17]
Hi Author:
    I have met a training error when using tensorflow-gpu==1.14. Could you please help me solve it? Thanks a lot.

Preparing reprojected indices for testing
Initiating input pipelines
****EPOCH 0****
Caught a NaN error :
3
ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_SensatUrban.py", line 135, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

         [[{{node PyFunc}}]]
         [[IteratorGetNext]]
None
Traceback (most recent call last):
  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_SensatUrban.py", line 135, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

         [[{{node PyFunc}}]]
         [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/home/******/SensatUrban/RandLANet.py", line 158, in train
    _, _, summary, l_out, probs, labels, acc = self.sess.run(ops, {self.is_training: True})
  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_SensatUrban.py", line 135, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/export/home/******anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

         [[{{node PyFunc}}]]
         [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_SensatUrban.py", line 265, in <module>
    model.train(dataset)
  File "/export/home/******/SensatUrban/RandLANet.py", line 196, in train
    print(e.op.name)
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by ltf020298** [comment]
I meet the same problem， have you solved it?

**Comment by lin1061991611** [comment]
> Hi Author:
> I have met a training error when using tensorflow-gpu==1.14. Could you please help me solve it? Thanks a lot.
> 
> Preparing reprojected indices for testing
> Initiating input pipelines
> ****EPOCH 0****
> Caught a NaN error :
> 3
> ValueError: attempt to get argmin of an empty sequence
> Traceback (most recent call last):
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
> return getattr(obj, method)(*args, **kwds)
> 
> AttributeError: 'list' object has no attribute 'argmin'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in **call**
> ret = func(*args)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
> values = next(generator_state.get_iterator(iterator_id))
> 
> File "main_SensatUrban.py", line 135, in spatially_regular_gen
> cloud_idx = int(np.argmin(self.min_possibility[split]))
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
> return _wrapfunc(a, 'argmin', axis=axis, out=out)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
> return _wrapit(obj, method, *args, **kwds)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
> result = getattr(asarray(obj), method)(*args, **kwds)
> 
> ValueError: attempt to get argmin of an empty sequence
> 
> ```
>      [[{{node PyFunc}}]]
>      [[IteratorGetNext]]
> ```
> 
> None
> Traceback (most recent call last):
> File "/export/home/__****/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call return fn(_args) File "/export/home/_****_/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn options, feed_dict, fetch_list, target_list, run_metadata) File "/export/home/_*****/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
> Traceback (most recent call last):
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
> return getattr(obj, method)(*args, **kwds)
> 
> AttributeError: 'list' object has no attribute 'argmin'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in **call**
> ret = func(*args)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
> values = next(generator_state.get_iterator(iterator_id))
> 
> File "main_SensatUrban.py", line 135, in spatially_regular_gen
> cloud_idx = int(np.argmin(self.min_possibility[split]))
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
> return _wrapfunc(a, 'argmin', axis=axis, out=out)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
> return _wrapit(obj, method, *args, **kwds)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
> result = getattr(asarray(obj), method)(*args, **kwds)
> 
> ValueError: attempt to get argmin of an empty sequence
> 
> ```
>      [[{{node PyFunc}}]]
>      [[IteratorGetNext]]
> ```
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/export/home/******/SensatUrban/RandLANet.py", line 158, in train _, _, summary, l_out, probs, labels, acc = self.sess.run(ops, {self.is_training: True}) File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
> run_metadata_ptr)
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run feed_dict_tensor, options, run_metadata) File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
> run_metadata)
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
> Traceback (most recent call last):
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
> return getattr(obj, method)(*args, **kwds)
> 
> AttributeError: 'list' object has no attribute 'argmin'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in **call**
> ret = func(*args)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
> values = next(generator_state.get_iterator(iterator_id))
> 
> File "main_SensatUrban.py", line 135, in spatially_regular_gen
> cloud_idx = int(np.argmin(self.min_possibility[split]))
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
> return _wrapfunc(a, 'argmin', axis=axis, out=out)
> 
> File "/export/home/******/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
> return _wrapit(obj, method, *args, **kwds)
> 
> File "/export/home/******anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
> result = getattr(asarray(obj), method)(*args, **kwds)
> 
> ValueError: attempt to get argmin of an empty sequence
> 
> ```
>      [[{{node PyFunc}}]]
>      [[IteratorGetNext]]
> ```
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "main_SensatUrban.py", line 265, in
> model.train(dataset)
> File "/export/home/******/SensatUrban/RandLANet.py", line 196, in train
> print(e.op.name)
> AttributeError: 'NoneType' object has no attribute 'name'

Hello，兄弟你后来是怎么解决的呀

**Comment by SuperKX** [comment]
@lin1061991611 @ltf020298 did you solve the problem?
