### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by whuhxb** [QingyongHu/SensatUrban#18]
Hi, 
   Have you ever met this problem? I have installed scikit-learn==0.21.3. Thanks.

Traceback (most recent call last):
  File "main_SensatUrban.py", line 260, in <module>
    dataset = SensatUrban()
  File "main_SensatUrban.py", line 48, in __init__
    self.load_sub_sampled_clouds(cfg.sub_grid_size)
  File "main_SensatUrban.py", line 79, in load_sub_sampled_clouds
    search_tree = pickle.load(f)
ImportError: No module named 'sklearn.neighbors._kd_tree'

**Comment by whuhxb** [comment]
Anyone knows how to solve this error? Thanks a lot.

**Comment by gunjupark** [comment]
have you solve this error??
